import logging
import asyncio
from typing import Optional
from concurrent.futures import ThreadPoolExecutor

try:
    import resend
except ImportError:
    resend = None

from .config import (
    RESEND_API_KEY,
    EMAIL_FROM_ADDRESS,
    EMAIL_FROM_NAME,
    APP_BASE_URL,
    is_email_configured
)

logger = logging.getLogger(__name__)

# Configure Resend SDK globally
if is_email_configured() and resend:
    resend.api_key = RESEND_API_KEY

# Thread pool for synchronous Resend API calls
_executor = ThreadPoolExecutor(max_workers=5)


def _render_password_reset_html(user_name: str, reset_url: str) -> str:
    """Render the HTML email template for password reset (Bilingual)."""
    # Simple HTML escaping
    safe_name = user_name.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
    
    return f"""<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>รีเซ็ตรหัสผ่าน Personal Data Bank</title>
    <style>
        body {{ font-family: sans-serif; line-height: 1.6; color: #333; }}
        .container {{ max-width: 600px; margin: 0 auto; padding: 20px; }}
        .button {{ display: inline-block; padding: 12px 24px; background-color: #007bff; color: white !important; text-decoration: none; border-radius: 4px; font-weight: bold; margin: 20px 0; }}
        .footer {{ margin-top: 40px; font-size: 12px; color: #777; border-top: 1px solid #ddd; padding-top: 20px; }}
        .en-section {{ color: #555; }}
    </style>
</head>
<body>
    <div class="container">
        <h2>สวัสดีคุณ {safe_name},</h2>
        <p>เราได้รับคำขอให้รีเซ็ตรหัสผ่านสำหรับบัญชี Personal Data Bank ของคุณ</p>
        <p>กรุณาคลิกปุ่มด้านล่างเพื่อตั้งรหัสผ่านใหม่ ลิงก์นี้จะหมดอายุใน 30 นาที</p>
        
        <a href="{reset_url}" class="button">รีเซ็ตรหัสผ่าน</a>
        
        <p>หากคุณไม่ได้ร้องขอการรีเซ็ตรหัสผ่าน คุณสามารถเพิกเฉยต่ออีเมลฉบับนี้ได้</p>
        
        <div class="footer">
            <div class="en-section">
                <p>Hello {safe_name},</p>
                <p>We received a request to reset the password for your Personal Data Bank account. Please click the button below to set a new password. This link expires in 30 minutes.</p>
                <a href="{reset_url}">Reset Password</a>
                <p>If you did not request this, you can safely ignore this email.</p>
            </div>
            <p><br>Personal Data Bank (PDB)</p>
        </div>
    </div>
</body>
</html>
"""

def _render_password_reset_text(user_name: str, reset_url: str) -> str:
    """Render the plain text email template for password reset."""
    return f"""สวัสดีคุณ {user_name},

เราได้รับคำขอให้รีเซ็ตรหัสผ่านสำหรับบัญชี Personal Data Bank ของคุณ
กรุณาไปที่ลิงก์ด้านล่างเพื่อตั้งรหัสผ่านใหม่ (ลิงก์นี้จะหมดอายุใน 30 นาที):

{reset_url}

หากคุณไม่ได้ร้องขอการรีเซ็ตรหัสผ่าน คุณสามารถเพิกเฉยต่ออีเมลฉบับนี้ได้
---
Hello {user_name},

We received a request to reset the password for your Personal Data Bank account.
Please visit the link below to set a new password (this link expires in 30 minutes):

{reset_url}

If you did not request this, you can safely ignore this email.

Personal Data Bank (PDB)
"""

def _send_sync(params: dict) -> dict:
    """Synchronous wrapper for resend.Emails.send to run in thread pool."""
    if not resend:
        raise ImportError("resend package is not installed.")
    return resend.Emails.send(params)

async def send_password_reset_email(to_email: str, user_name: str, reset_token: str) -> bool:
    """Send a password reset email asynchronously via Resend.
    
    Args:
        to_email: Recipient email address
        user_name: User's display name
        reset_token: Valid reset token generated by auth.py
        
    Returns:
        bool: True if sent successfully, False if email service not configured or failed
    """
    if not is_email_configured():
        logger.warning(f"Email service not configured. Could not send password reset to {to_email}")
        return False
        
    reset_url = f"{APP_BASE_URL.rstrip('/')}/reset-password?token={reset_token}"
    
    html_content = _render_password_reset_html(user_name, reset_url)
    text_content = _render_password_reset_text(user_name, reset_url)
    
    params = {
        "from": f"{EMAIL_FROM_NAME} <{EMAIL_FROM_ADDRESS}>",
        "to": [to_email],
        "subject": "รีเซ็ตรหัสผ่าน Personal Data Bank",
        "html": html_content,
        "text": text_content,
    }
    
    try:
        loop = asyncio.get_running_loop()
        response = await loop.run_in_executor(_executor, _send_sync, params)
        logger.info(f"Password reset email sent to {to_email}, resend_id={response.get('id')}")
        return True
    except Exception as e:
        logger.error(f"Failed to send password reset email to {to_email}: {str(e)}")
        return False
